<?php

function hiremodule_menu(){
	$items['equipment'] = array(
		'title' =>'Hire Equipment',
		'page callback' => 'bw_hire_equipment_page',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM,
	);
    // $items['equipment/hire'] = array(
    //  'page callback' => 'hello_malaka'
    // );
	return $items;
}

function bw_hire_equipment_page(){
    return bw_list_equipment(BWEquipment::getAll());

    // $action = $_GET['action'];
    //         
    //     module_load_include('inc', 'hiremodule', 'hire_equipment_page');
    //  
    //  if($_SERVER['REQUEST_METHOD'] == 'GET'){
    //      if(isset($action)) {
    //          c->strtolower($_SERVER['REQUEST_METHOD'])->$action();
    //      }
    //  } else {
    //      
    //  }
		
    // else{        
    //     return bw_list_equipment(BWEquipment::getAll());
    // }    
}

// who can use this module?
function hiremodule_perm() {
    // need to create different permisisons here
    return array('Hire', 'Manage');
}

class BWEquipmentController {
    class get{
        function update(){
            $equipment = array("id" => 1, "category" => "tent", "name" => "Tent 3 man", "description" => "good for 3 man", "price" => 10 );
            $action_name = "update";
            $action_path = ""
            return bw_equipment_form();
        }
    }
    
    // class post{
    //     function update(){
    //         return "the update worked";
    //     }
    // }
}


class BWEquipment {
    function getAll(){
        return array(
            array("id" => 1, "category" => "tent", "name" => "Tent 3 man", "description" => "good for 3 man", "price" => 10 ),
            array("id" => 2, "category" => "tent", "name" => "Tent 6 man", "description" => "good for 6 man", "price" => 20 ),
            array("id" => 3, "category" => "backpack", "name" => "backpack", "description" => "a backpack", "price" => 2 ),
            array("id" => 4, "category" => "shoes", "name" => "hiking shoes", "description" => "good for hiking", "price" => 5 ),
        );
    }
}

?>