<?php

function hiremodule_menu(){
	$items['hire'] = array(
		'title' =>'Hire Equipment',
		'page callback' => 'bw_hire_equipment_page',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM,
	);
	
	$items['equipment'] = array(
		'title' =>'Manage Equipment',
		'page callback' => 'bw_equipment_page',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM,
	);
	
    // $items['equipment/hire'] = array(
    //  'page callback' => 'hello_malaka'
    // );
	return $items;
}

function bw_hire_equipment_page(){
    module_load_include('inc', 'hiremodule', 'hire_equipment_page');
    
    $action = $_REQUEST['action'];
        
    if($action){
        $method = "bw_".strtolower($_SERVER['REQUEST_METHOD']) ."_$action";
        return $method();
    }
    
    return bw_list_equipment(BWEquipment::getAll());
}

function bw_equipment_page(){
    module_load_include('inc', 'hiremodule', 'equipment_page');
    
    $action = $_REQUEST['action'];
        
    if($action){
        $method = "bw_".strtolower($_SERVER['REQUEST_METHOD']) ."_$action";
        return $method();
    }
    
    return bw_list_equipment(BWEquipment::getAll());
}

// who can use this module?
function hiremodule_perm() {
    return array('Hire', 'Manage');
}

// HIRE things

function bw_get_update(){ 
    // FIXME get from db
    $equipment = array("id" => 1, "category" => "tent", "name" => "Tent 3 man", "description" => "good for 3 man", "price" => 10 );
    return bw_equipment_form($equipment, "update", "");
}

function bw_post_update(){
    drupal_set_message('Equipment updated');
    drupal_goto('equipment');
}

function bw_get_delete(){
    drupal_set_message('Equipment deleted');
    drupal_goto('equipment');
}

function bw_post_book(){
    // FIXME update in db
    drupal_set_message('Equipment has been booked');
    drupal_goto('equipment');
}

class BWEquipment {
    // FIXME get from db
    function getAll(){
        return array(
            array("id" => 1, "category" => "tent", "name" => "Tent 3 man", "description" => "good for 3 man", "price" => 10 ),
            array("id" => 2, "category" => "tent", "name" => "Tent 6 man", "description" => "good for 6 man", "price" => 20 ),
            array("id" => 3, "category" => "backpack", "name" => "backpack", "description" => "a backpack", "price" => 2 ),
            array("id" => 4, "category" => "shoes", "name" => "hiking shoes", "description" => "good for hiking", "price" => 5 ),
        );
    }
}
?>