<?php

function testmodule_menu(){
	$items['myTestForm'] = array(
		'title' =>'Bushwalking Test Module',
		'page callback' => 'bw_testmodule_page',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM,
	);
	
	$items['myTestForm2'] = array(
		'title' =>'Bushwalking Test Module',
		'page callback' => 'bw_testmodule_page',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM,
	);
	
	$items['myTestForm3'] = array(
		'title' =>'Bushwalking Test Module',
		'page callback' => 'bw_testmodule_page',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM,
	);
	
	return $items;
}

function bw_testmodule_page(){
	module_load_include('inc', 'testmodule', 'testmodule_pages');
	return drupal_get_form('bw_testmodule_form');
}

function testmodule_perm() {
  return array('Hire', 'Manage');
}

?>