<?php

function oosdmodule_menu(){
	$items['hire_equipment'] = array(
		'title' =>'Hire Equipment',
		'page callback' => 'bw_hire_equipment_page',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM,
	);
	
	$items['equipment'] = array(
		'title' =>'Manage Equipment',
		'page callback' => 'bw_equipment_page',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM,
	);
    return $items;
}

// TODO refactor same as bw_equipment_page
function bw_hire_equipment_page(){
    module_load_include('inc', 'oosdmodule', 'hire_equipment_page');
    $method = bw_get_method();
    return $method();
}

function bw_equipment_page(){
    module_load_include('inc', 'oosdmodule', 'equipment_page');
    $method = bw_get_method();
    return $method();
}

function bw_get_method(){
    $method = "bw_index";
    $action = $_REQUEST['action'];
    
    if($action){
        $method = "bw_".strtolower($_SERVER['REQUEST_METHOD']) ."_$action";
    }
    return $method;
}

// who can use this module?
function oosdmodule_perm() {
    return array('Hire', 'Manage');
}

?>