<?php

function oosdmodule_menu(){
	$items['hire_equipment'] = array(
		'title' =>'Hire Equipment',
		'page callback' => 'bw_hire_equipment_page',
        'access arguments' => array('hire equipment'),
		'type' => MENU_NORMAL_ITEM,
	);
	
	$items['manage_equipment'] = array(
		'title' =>'Manage Equipment',
		'page callback' => 'bw_equipment_page',
        'access arguments' => array('manage equipment'),
        'type' => MENU_NORMAL_ITEM,
	);
	
	$items['manage_hire'] = array(
		'title' =>'Manage Hire',
		'page callback' => 'bw_hire_page',
		'access arguments' => array('manage hire'),
		'type' => MENU_NORMAL_ITEM,
	);
    return $items;
}

function bw_hire_equipment_page(){
    module_load_include('inc', 'oosdmodule', 'hire_equipment_page');
    $method = bw_get_method();
    return $method();
}

function bw_equipment_page(){
    module_load_include('inc', 'oosdmodule', 'equipment_page');
    $method = bw_get_method();
    return $method();
}

function bw_hire_page(){
    module_load_include('inc', 'oosdmodule', 'hire_page');
    $method = bw_get_method();
    return $method();
}


function bw_get_method(){
    $method = "bw_index";
    $action = $_REQUEST['action'];
    
    if($action){
        $method = "bw_".strtolower($_SERVER['REQUEST_METHOD']) ."_$action";
    }
    return $method;
}

// who can use this module?
function oosdmodule_perm() {
    return array('hire equipment', 'manage equipment', 'manage hire');
    
}

?>