<?php
/***********************************************************************************
#  University: RMIT University - Melbourne, Australia
# School: Computer Science and Information Technology
# Subject:  ISYS1083 Object Oriented Software Design
# Assignment : Final OOSD Group Assignment
# Project Title: Bushwalking Web Site
#  Semester:  1 - 2011
---------------------------------------------------------------------------------
Hire equipment Module

Module is responsible to handle all admin and users functionality
Users/Members  can hire and  equipment  with the given dates if equipment  is available
Administrators can manage equipments (Create, Read, Upade, Delete)
Administrators can manage hires (user hire an equipment) Create, Read, Upade, Delete

Group Members:
* Amruta Varshini - TL (s3272373)
* Emil B. Kjer (s3298554)
* Victor Nava (s3252905)
* John Kolovos (s3289732)
* Stefan Fuch (s3260968)
---------------------------------------------------------------------------------
@author Victor Nava
@author John Kolovos
***********************************************************************************/

function oosdmodule_menu(){
	$items['hire_equipment'] = array(
		'title' =>'Hire Equipment',
		'page callback' => 'bw_hire_equipment_page',
        'access arguments' => array('hire equipment'),
		'type' => MENU_NORMAL_ITEM,
	);
	
	$items['equipment'] = array(
		'title' =>'Manage Equipment',
		'page callback' => 'bw_equipment_page',
        'access arguments' => array('manage equipment'),
        'type' => MENU_NORMAL_ITEM,
	);
	
	$items['hire'] = array(
		'title' =>'Manage Hire',
		'page callback' => 'bw_hire_page',
		'access arguments' => array('manage hire'),
		'type' => MENU_NORMAL_ITEM,
	);
    return $items;
}

function bw_hire_equipment_page(){
    module_load_include('inc', 'oosdmodule', 'hire_equipment_page');
    $method = bw_get_method();
    return $method();
}

function bw_equipment_page(){
    module_load_include('inc', 'oosdmodule', 'equipment_page');
    $method = bw_get_method();
    return $method();
}

function bw_hire_page(){
    module_load_include('inc', 'oosdmodule', 'hire_page');
    $method = bw_get_method();
    return $method();
}


function bw_get_method(){
    $method = "bw_index";
    $action = $_REQUEST['action'];
    
    if($action){
        $method = "bw_".strtolower($_SERVER['REQUEST_METHOD']) ."_$action";
    }
    return $method;
}

function oosdmodule_perm() {
    return array('hire equipment', 'manage equipment', 'manage hire');
    
}
?>